In [29]:
import pandas as pd
import numpy as np

In [30]:
data = pd.read_csv('cell sample.csv')
data.head()

ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc   
0  1000025      5         1          1        1            2       1  \
1  1002945      5         4          4        5            7      10   
2  1015425      3         1          1        1            2       2   
3  1016277      6         8          8        1            3       4   
4  1017023      4         1          1        3            2       1   

   BlandChrom  NormNucl  Mit  Class  
0           3         1    1      2  
1           3         2    1      2  
2           3         1    1      2  
3           3         7    1      2  
4           3         1    1      2

In [32]:
data2 = data[['Clump','UnifSize','UnifShape','MargAdh','SingEpiSize','BareNuc','BlandChrom']]
data2.head()
data2.values

array([[5, 1, 1, ..., 2, '1', 3],
       [5, 4, 4, ..., 7, '10', 3],
       [3, 1, 1, ..., 2, '2', 3],
       ...,
       [5, 10, 10, ..., 7, '3', 8],
       [4, 8, 6, ..., 3, '4', 10],
       [4, 8, 8, ..., 4, '5', 10]], dtype=object)

In [33]:
data = data2.iloc[:4,:4]
data = np.array(data)
data

array([[5, 1, 1, 1],
       [5, 4, 4, 5],
       [3, 1, 1, 1],
       [6, 8, 8, 1]], dtype=int64)

In [35]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

A = data
U, s, V = svd(A)

n_elements = 2
Sigma = A[:, :n_elements]
V = V[:n_elements, :]
B = U.dot(Sigma.dot(V))
print(B)

[[-0.94621985 -0.05042621 -0.05042621 -0.74119139]
 [ 1.59041407  1.39551777  1.39551777  0.72002963]
 [ 0.69841324 -7.20707057 -7.20707057  3.45290135]
 [ 2.06495261  4.89682601  4.89682601 -0.30255232]]


In [37]:
T = U.dot(Sigma)
print(T)

[[ 0.78158292 -0.91592053]
 [-2.63151979  0.1338015 ]
 [ 6.70645974  8.44496531]
 [-6.51825356 -3.13460486]]
